### ISSUE TITLE
Latest Parse possible?

### ISSUE THREAD

**Issue by renegens** [yongjhih/RxParse#11]
Hello, 

is it possible to use the lib with the latest Parse sdk. I understand that you have an internal dependency at a lower level parse implementation.

**Comment by renegens** [comment]
Or even just add the file as a helper class, but then I have problems with lambdas which I don't support.

**Comment by markmssd** [comment]
I've tried upgrading to latest version, but had dependencies versions conflicting with each other
    - rxJava
    - rxAndroid
    - Bolts
    - rxAssertions

Can someone else give it a try?

**Comment by yongjhih** [comment]
Actually, you can just specify latest parse sdk version in main project. However, i updated rxparse for latest parse deps.

https://github.com/yongjhih/RxParse/releases/tag/2.0.3
