### ISSUE TITLE
Support RxJava2

### ISSUE THREAD

**Issue by yongjhih** [yongjhih/RxParse#14]

**Comment by johnernest02** [comment]
Hello, are there any updates or timeline for this?

**Comment by yongjhih** [comment]
Hi @dev-JE02,
it's pending for a long time. But I think I can finish it this weekend if you are eager.

**Comment by johnernest02** [comment]
Yes if at all possible please

**Comment by tmingos** [comment]
You are amazing!

**Comment by johnernest02** [comment]
Thank you very much!

**Comment by vxhviet** [comment]
Sorry @yongjhih , after failing to retrieve version `2.0.4` from `jcenter()` with `compile 'com.infstory:rxparse:2.0.4'`, I quickly check the [jcenter index](https://repo.spring.io/jcenter/com/infstory/rxparse/)  and it seems like version 2.0.4 is missing.

Is it got pulled from jcenter somehow?

**Comment by yongjhih** [comment]
@vxhviet ,

Sorry, I forgot to upload into jcenter. I'm going to upload that into jcenter for a while. Can you download that from jitpack instead by the following configuration?

```gradle
repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.yongjhih.RxParse:rxparse2:-SNAPSHOT'
}
```
