### ISSUE TITLE
ParseObservable.save(objects: (Mutable)List<R!>!) doesn't emit R values

### ISSUE THREAD

**Issue by KamilS91** [yongjhih/RxParse#19]
When I'm using `ParseObservable.save(objects: (Mutable)List<R!>!): Observable<R!>` I got `Observable`, which don't emit `R` objects, although save is completed successfully.

**Comment by yongjhih** [comment]
Are you using RxParse1 or 2?

It's a known issue in RxParse2. We should change the `Obseravable` to `Completable` for that.

**Comment by KamilS91** [comment]
I'm using RxParse2 and Kotlin. What do you mean by 

> We should change to Obseravable to Completable for that

It would be only Completable, because of no data emitted and currently there is no way to got those data, which have been saved?

**Comment by yongjhih** [comment]
@KamilS91 
It's a typo, we should change to Completable exactly. And you can see my changes in the 557a7c5 .
